databases:
  - name: learning_log
    plan: free
    databaseName: learning_log_db
    user: aslan

services:
  - type: web
    plan: free
    name: learning_log
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn learning_log.wsgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: learning_log
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4